#version: '3.5'
#
#
#services:
#
#  db_auth:
#    container_name: db
#    ports:
#      - "5432:5432"
#
#    environment:
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_USER=root
#      - POSTGRES_DB="postgresql"
#    image: postgres:alpine
#

version: '3.9'

services:

  db_auth:
    image: postgres:alpine

    container_name: db

    hostname: db
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres_db






  nudges:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src
    ports:
      - "80:80"
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=root
    - POSTGRES_DB=postgres_db
    depends_on:
      - db_auth
