version: '3.5'


services:
  
  db_auth: 
    container_name: db
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB="postgresql"
    image: postgres:alpine